# Generated by Django 2.2.7 on 2019-12-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesave',
            name='title',
            field=models.TextField(default='', verbose_name='title'),
        ),
    ]
